App.Endpoint.Razor/Pages/User/Login.cshtml.cs
using App.Domain.Core.Contract.User;
using App.Domain.Core.Entites.Config;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace App.Endpoint.Razor.Pages.User
{
    public class LoginViewModel
    {
        public string Username { get; set; }
        public string Password { get; set; }
    }

    public class LoginModel : PageModel
    {
        private readonly SiteSetting _siteSettings;
        private readonly IUseAppService _userAppService;

        public LoginModel(SiteSetting siteSettings, IUseAppService userAppService)
        {
            _siteSettings = siteSettings;
            _userAppService = userAppService;
        }

        [BindProperty]
        public LoginViewModel PageModel { get; set; }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            IdentityResult result = await _userAppService.Login(PageModel.Username, PageModel.Password);

            if (result.Succeeded)
            {
                TempData["Success"] = "وارد شدید";
                return RedirectToPage("/Task/ListTask");
            }
            else
            {
                TempData["Error"] = "نام کاربری یا رمز عبور نادرست است";
                return RedirectToPage("/User/Login");
            }
        }

    }
}

App.Endpoint.Razor/Pages/User/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace App.Endpoint.Razor.Pages.User
{
    public class LogoutModel : PageModel
    {
        public void OnGet()
        {
        }

        public IActionResult OnGetLogOut()
        {
            HttpContext.Response.Cookies.Delete("ApiKey");

            return RedirectToPage("/User/Login");
        }
    }
}

App.Endpoint.Razor/Pages/User/Register.cshtml.cs
using App.Domain.Core.Contract.User;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace App.Endpoint.Razor.Pages.User
{
    public class CreateModel : PageModel
    {
        private readonly IUseAppService _userAppService;

        public CreateModel(IUseAppService userAppService)
        {
            _userAppService = userAppService;
        }

        [BindProperty]
        public Domain.Core.Entites.User User { get; set; }


        public async System.Threading.Tasks.Task OnGet(CancellationToken cancellationToken)
        {
            
        }


        public async Task<IActionResult> OnPost(CancellationToken cancellationToken)
        {
           await _userAppService.Register(User, cancellationToken);
            return RedirectToPage("Login");
        }
    }
}

App.Endpoint.Razor/Pages/User/Login.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model LoginModel
@{
}

@{
    Layout = "_Layout_Castum";
}


@if (TempData["Success"] != null)

{
    <div class="alert alert-primary" role="alert">
        <samp>
            @TempData["Success"].ToString()

        </samp>
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger" role="alert">
        <samp>
            @TempData["Error"].ToString()
        </samp>
    </div>
}


<div class="container px-5 my-5" >
    <form method="post">
        <div class="form-floating mb-3">
            <input class="form-control" asp-for="PageModel.Username" placeholder="نام کاربری" />
            <label for="username">نام کاربری</label>
        </div>
        <div class="form-floating mb-3">
            <input class="form-control" asp-for="PageModel.Password" type="password" placeholder="رمز عبور" />
            <label for="password">رمز عبور</label>
        </div>
        <div class="d-grid">
            <button class="btn btn-dark btn-lg " id="submitButton" type="submit">ورود</button>
        </div>
    </form>
</div>

App.Endpoint.Razor/Pages/User/Logout.cshtml
@page
@model LogoutModel
@{
}
<div class="container px-5 my-5">
    <div class="d-grid">
        <a asp-page-handler="LogOut" class="btn btn-dark btn-lg " id="submitButton" type="submit">خروج</a>
    </div>
</div>

App.Endpoint.Razor/Pages/User/Register.cshtml
@page
@model CreateModel


@{
    Layout = "_Layout_Castum";
}

@{
    ViewData["Title"] = "وظایف";

}@if (TempData["Error"] != null)
 {
     <div class="alert alert-danger" role="alert">
         <samp>
             @TempData["Error"].ToString()
         </samp>
     </div>
 }

<div class="col-lg-12">
    <div class="portlet box shadow">
        <div class="portlet-heading">
            <div class="portlet-title">
                <h3 class="title">
                    کاربران
                </h3>
            </div><!-- /.portlet-title -->
        </div><!-- /.portlet-heading -->
        <div class="portlet-body">
            <div class="top-buttons-box mb-2">
            </div>
            <div class="row">
                <form enctype="multipart/form-data" id="simple-form" role="form" method="post">
                    <div class="form-body">
                        <div class="form-group">
                            <div class="input-group">
                                <input asp-for="User.Email" class="form-control" type="email" placeholder="آدرس ایمیل" required />
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <input asp-for="User.UserName" class="form-control" type="text" placeholder="نام کاربری" />
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <input asp-for="User.PasswordHash" class="form-control" type="password" placeholder="کلمه عبور" />
                            </div>
                        </div>


                    </div>
                    <hr>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-success">
                            <i class="icon-check"></i>
                            ذخیره
                        </button>
                        <a asp-page="Index" class="btn btn-warning">
                            بازگشت
                        </a>
                    </div>
                </form>
            </div>
        </div><!-- /.portlet-body -->
    </div><!-- /.portlet -->
</div><!-- /.col-lg-12 -->